name: Building price scraper

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: getsentry/action-setup-venv@v2.1.0
      id: venv
      with:
        python-version: 3.11
        cache-dependency-path: |
          requirements.txt
          requirements-frozen.txt
        install-cmd: pip install -r requirements.txt -c requirements-frozen.txt
    - name: Test build
      run: |
        cd price_scraper
        scrapy crawl aranykor -a base_dir=../test-dir -L INFO
        scrapy crawl mak -a base_dir=../test-dir -L INFO
        scrapy crawl bamosz -a base_dir=../test-dir -L INFO
        scrapy crawl otp_nyugdij -a base_dir=../test-dir -L INFO
        scrapy crawl budapest_nyugdij -a base_dir=../test-dir -L INFO
        scrapy crawl mbh_nyugdij -a base_dir=../test-dir -L INFO
        scrapy crawl horizont_nyugdij -a base_dir=../test-dir -L INFO
        scrapy crawl allianz_nyugdij -a base_dir=../test-dir -L INFO

